import type { DriverLevel, TierBenefitsConfig, TierRequirements } from '@/types/driverRewards'
import { syncBenefitFlags } from '@/features/driver-rewards/utils/tierConfigHelpers'

export const DEFAULT_TIER_COLORS: Record<string, string> = {
  journey: '#64748b',
  pro: '#6366f1',
  pro_go: '#6366f1',
  elite: '#22d3ee',
  platinum: '#a855f7',
  diamond: '#f59e0b',
}

export const DEFAULT_TIER_BADGES: Record<string, string> = {
  journey: 'J',
  pro: 'PG',
  pro_go: 'PG',
  elite: 'E',
  platinum: 'PL',
  diamond: 'D',
}

export const DEFAULT_TIER_ICONS: Record<string, string> = {
  journey: 'route',
  pro: 'zap',
  pro_go: 'zap',
  elite: 'star',
  platinum: 'gem',
  diamond: 'crown',
}

type BenefitPreset = Omit<TierBenefitsConfig, 'flags'>

const DEFAULT_BENEFIT_PRESETS: Record<string, BenefitPreset> = {
  journey: {
    destinationFilters: 1,
    dailyUsageLimit: 2,
    weeklyUsageLimit: 8,
    filterExpirationHours: 4,
    filterCooldownHours: 2,
    filterCooldownRule: 'Filters expire 4 hours after activation',
    reservationAccess: 'none',
    advanceBookingAccess: false,
    reservationPriority: 0,
    maxReservationDistanceMiles: 0,
    reservationQueuePriority: 0,
    dispatchPriorityLevel: 1,
    rideMatchingPriority: 1,
    preferredRideAllocation: false,
    bonusMultiplier: 1,
    peakHourMultiplier: 1,
    airportRideBonusEnabled: false,
    scheduledRideBonusEnabled: false,
    referralBonusMultiplier: 1,
    cancellationProtection: false,
    disputePriority: false,
    customerSupportLevel: 'standard',
    vipSupportAccess: false,
    minimumAcceptanceRate: 80,
    minimumCompletionRate: 90,
    minimumDriverRating: 4.5,
    maximumComplaintThreshold: 5,
    promotionEligibility: false,
    campaignAccess: false,
    specialEventBonuses: false,
    seasonalIncentives: false,
  },
  pro_go: {
    destinationFilters: 2,
    dailyUsageLimit: 4,
    weeklyUsageLimit: 16,
    filterExpirationHours: 6,
    filterCooldownHours: 2,
    filterCooldownRule: 'Filters expire 6 hours after activation',
    reservationAccess: 'standard',
    advanceBookingAccess: true,
    reservationPriority: 2,
    maxReservationDistanceMiles: 25,
    reservationQueuePriority: 2,
    dispatchPriorityLevel: 2,
    rideMatchingPriority: 2,
    preferredRideAllocation: false,
    bonusMultiplier: 1.05,
    peakHourMultiplier: 1.02,
    airportRideBonusEnabled: true,
    scheduledRideBonusEnabled: false,
    referralBonusMultiplier: 1.1,
    cancellationProtection: false,
    disputePriority: false,
    customerSupportLevel: 'standard',
    vipSupportAccess: false,
    minimumAcceptanceRate: 85,
    minimumCompletionRate: 92,
    minimumDriverRating: 4.5,
    maximumComplaintThreshold: 4,
    promotionEligibility: true,
    campaignAccess: true,
    specialEventBonuses: false,
    seasonalIncentives: false,
  },
  elite: {
    destinationFilters: 3,
    dailyUsageLimit: 6,
    weeklyUsageLimit: 24,
    filterExpirationHours: 8,
    filterCooldownHours: 1,
    filterCooldownRule: 'Filters expire 8 hours after activation',
    reservationAccess: 'standard',
    advanceBookingAccess: true,
    reservationPriority: 3,
    maxReservationDistanceMiles: 40,
    reservationQueuePriority: 3,
    dispatchPriorityLevel: 3,
    rideMatchingPriority: 3,
    preferredRideAllocation: true,
    bonusMultiplier: 1.1,
    peakHourMultiplier: 1.05,
    airportRideBonusEnabled: true,
    scheduledRideBonusEnabled: true,
    referralBonusMultiplier: 1.15,
    cancellationProtection: true,
    disputePriority: false,
    customerSupportLevel: 'priority',
    vipSupportAccess: false,
    minimumAcceptanceRate: 90,
    minimumCompletionRate: 95,
    minimumDriverRating: 4.7,
    maximumComplaintThreshold: 3,
    promotionEligibility: true,
    campaignAccess: true,
    specialEventBonuses: true,
    seasonalIncentives: false,
  },
  platinum: {
    destinationFilters: 4,
    dailyUsageLimit: 8,
    weeklyUsageLimit: 32,
    filterExpirationHours: 12,
    filterCooldownHours: 1,
    filterCooldownRule: 'Filters expire 12 hours after activation',
    reservationAccess: 'priority',
    advanceBookingAccess: true,
    reservationPriority: 4,
    maxReservationDistanceMiles: 60,
    reservationQueuePriority: 4,
    dispatchPriorityLevel: 4,
    rideMatchingPriority: 4,
    preferredRideAllocation: true,
    bonusMultiplier: 1.2,
    peakHourMultiplier: 1.08,
    airportRideBonusEnabled: true,
    scheduledRideBonusEnabled: true,
    referralBonusMultiplier: 1.2,
    cancellationProtection: true,
    disputePriority: true,
    customerSupportLevel: 'priority',
    vipSupportAccess: true,
    minimumAcceptanceRate: 92,
    minimumCompletionRate: 96,
    minimumDriverRating: 4.8,
    maximumComplaintThreshold: 2,
    promotionEligibility: true,
    campaignAccess: true,
    specialEventBonuses: true,
    seasonalIncentives: true,
  },
  diamond: {
    destinationFilters: 5,
    dailyUsageLimit: 10,
    weeklyUsageLimit: 40,
    filterExpirationHours: 24,
    filterCooldownHours: 0,
    filterCooldownRule: 'Filters expire 24 hours after activation',
    reservationAccess: 'exclusive',
    advanceBookingAccess: true,
    reservationPriority: 5,
    maxReservationDistanceMiles: 100,
    reservationQueuePriority: 5,
    dispatchPriorityLevel: 5,
    rideMatchingPriority: 5,
    preferredRideAllocation: true,
    bonusMultiplier: 1.35,
    peakHourMultiplier: 1.12,
    airportRideBonusEnabled: true,
    scheduledRideBonusEnabled: true,
    referralBonusMultiplier: 1.35,
    cancellationProtection: true,
    disputePriority: true,
    customerSupportLevel: 'vip',
    vipSupportAccess: true,
    minimumAcceptanceRate: 95,
    minimumCompletionRate: 98,
    minimumDriverRating: 4.9,
    maximumComplaintThreshold: 1,
    promotionEligibility: true,
    campaignAccess: true,
    specialEventBonuses: true,
    seasonalIncentives: true,
  },
}

export function createTierRequirements(partial: Partial<TierRequirements> = {}): TierRequirements {
  return {
    completedTrips: 0,
    driverRating: 4.5,
    acceptanceRate: 80,
    cancellationRate: 10,
    onlineHours: 0,
    consecutiveActiveDays: 0,
    customerSatisfactionScore: 80,
    safetyScore: 85,
    complianceScore: 90,
    fraudScore: 95,
    incidentCount: 0,
    ...partial,
  }
}

export function createDefaultLevel(
  id: string,
  name: string,
  label: string,
  description: string,
  level: number,
  sortOrder: number,
  requirements: Partial<TierRequirements>,
  benefits?: Partial<TierBenefitsConfig>,
  driverCount = 0,
  requiredPoints?: number,
): DriverLevel {
  const presetKey = name === 'pro' ? 'pro_go' : name
  const basePreset = DEFAULT_BENEFIT_PRESETS[presetKey] ?? DEFAULT_BENEFIT_PRESETS.journey
  const req = createTierRequirements(requirements)
  const mergedBenefits = syncBenefitFlags({
    ...basePreset,
    ...benefits,
    minimumAcceptanceRate: benefits?.minimumAcceptanceRate ?? req.acceptanceRate,
    minimumCompletionRate: benefits?.minimumCompletionRate ?? Math.min(req.acceptanceRate + 5, 99),
    minimumDriverRating: benefits?.minimumDriverRating ?? req.driverRating,
  })

  return {
    id,
    name,
    slug: name.replace(/_/g, '-'),
    label,
    description,
    level,
    icon: DEFAULT_TIER_ICONS[name] ?? 'award',
    requiredPoints: requiredPoints ?? req.completedTrips * 10,
    requiredRating: req.driverRating,
    requiredTrips: req.completedTrips,
    requiredOnlineHours: req.onlineHours,
    requiredAcceptanceRate: req.acceptanceRate,
    requiredCompletionRate: mergedBenefits.minimumCompletionRate,
    requirements: req,
    benefits: mergedBenefits,
    tierColor: DEFAULT_TIER_COLORS[name] ?? '#6366f1',
    tierBadge: DEFAULT_TIER_BADGES[name] ?? label.slice(0, 2).toUpperCase(),
    benefitsCount: 0,
    driverCount,
    status: 'active',
    sortOrder,
  }
}

export function createPointsRule(
  id: string,
  ruleName: string,
  actionType: string,
  points: number,
  category: import('@/types/driverRewards').PointsRuleCategory = 'ride_completion',
): import('@/types/driverRewards').PointsRule {
  const type: import('@/types/driverRewards').PointsRuleType = points > 0 ? 'earn' : points < 0 ? 'deduct' : 'neutral'
  return {
    id,
    ruleName,
    action: ruleName,
    actionType,
    category,
    points,
    type,
    status: 'active',
    lastUpdated: new Date().toISOString(),
  }
}

export const TIER_REQUIREMENT_FIELDS: Array<{ key: keyof TierRequirements; label: string }> = [
  { key: 'completedTrips', label: 'Completed Trips' },
  { key: 'driverRating', label: 'Driver Rating' },
  { key: 'acceptanceRate', label: 'Acceptance Rate (%)' },
  { key: 'cancellationRate', label: 'Cancellation Rate (%)' },
  { key: 'onlineHours', label: 'Online Hours' },
  { key: 'consecutiveActiveDays', label: 'Consecutive Active Days' },
  { key: 'customerSatisfactionScore', label: 'Customer Satisfaction Score' },
  { key: 'safetyScore', label: 'Safety Score' },
  { key: 'complianceScore', label: 'Compliance Score' },
  { key: 'fraudScore', label: 'Fraud Score' },
  { key: 'incidentCount', label: 'Incident Count (max)' },
]

export const TIER_BENEFIT_FLAG_FIELDS: Array<{ key: keyof TierBenefitsConfig['flags']; label: string }> = [
  { key: 'priorityDispatch', label: 'Priority Dispatch' },
  { key: 'priorityMatching', label: 'Priority Matching' },
  { key: 'premiumRideAccess', label: 'Premium Ride Access' },
  { key: 'airportQueuePriority', label: 'Airport Queue Priority' },
  { key: 'eventQueuePriority', label: 'Event Queue Priority' },
  { key: 'vipRideAccess', label: 'VIP Ride Access' },
  { key: 'luxuryRideAccess', label: 'Luxury Ride Access' },
  { key: 'dedicatedSupport', label: 'Dedicated Support' },
  { key: 'reservationPriority', label: 'Reservation Priority' },
  { key: 'earlyFeatureAccess', label: 'Early Feature Access' },
]

export const TIER_MANAGEMENT_PATH = '/drivers/tiers'
