export { default as LoginPage } from './LoginPage'
export { default as ForgotPasswordPage } from './ForgotPasswordPage'
export { default as OtpVerificationPage } from './OtpVerificationPage'
export { default as ResetPasswordPage } from './ResetPasswordPage'
export { default as PasswordUpdatedPage } from './PasswordUpdatedPage'
